version: "2"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./web/:/var/www/web
      - ./web/public/upload:/var/www/web/public/upload
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/web
    links:
      - phpfpm
    ports:
      - 8080:80
  phpfpm:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./web/:/var/www/web
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - db:mysql
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=christmas
      - MYSQL_USER=vFm3bgwG6V
      - MYSQL_PASSWORD=fLFcfhaEkLiR6rFmY8wU
      - MYSQL_ROOT_PASSWORD=hra22aQ3Zru33esczPnfwByxLDJMZHZn88Z9ZUL2Ma47frcRRC
  phpmyadmin:
    image: nazarpc/phpmyadmin
    links:
      - db:mysql
    ports:
      - 5678:80
volumes:
  mysql-data:
    driver: local
